from langchain.chat_models import ChatOpenAI
from langchain.prompts import PromptTemplate
from langchain.chains.openai_functions import create_structured_output_chain
from pprint import pprint

# from llm.constants import GPT_3_MODEL, GPT_4_MODEL, TEST_TEXT

GPT_3_MODEL = "gpt-3.5-turbo-0125"
GPT_4_MODEL = "gpt-4"
GPT_4_TURBO_MODEL = "gpt-4-turbo-preview"

TEST_TEXT = """
Like a lot of explosive financial scandals, the story of Michael Quinn and Brendan Cahill could fairly be described as a simple proposition that spun completely out of control.
Listen to This Article

Quinn was an Irish oil-and-gas man with warm eyes and a mustache; Cahill was his longtime partner, an accountant by training. The two had been working in Nigeria since the 1970s, doing small-time deals in the energy and defense sectors, like fixing tanks and siting oil wells. But in the mid-2000s, they spied a bigger opportunity. They knew that Nigeria’s refineries were burning off most of the gas that was recovered during oil drilling — a practice that poisoned the atmosphere and deprived the country of a source of electricity. Quinn and Cahill proposed a “gas leaning” plant, which would take in the “wet” gas that would otherwise be flared and spit out “lean” gas that could actually power the grid. It would transform waste into fuel.
Quinn and Cahill founded a new company for this purpose and gave it a forgettable name, Process and Industrial Developments Ltd. The two worked out of an office in Abuja, Nigeria’s capital. But P.&I.D.’s legal address was a P.O. box on Tortola, in the British Virgin Islands. This could shield the new entity from taxes and scrutiny, while also making it easier to raise capital on the international markets.

The next step was to draw a proposal for the Ministry of Petroleum Resources, the department that oversees Nigeria’s considerable fossil-fuel reserves. P.&I.D. would construct the $500 million facility. Nigeria would pipe in wet gas at no cost to the company. Then P.&I.D. would process it and pipe out the lean gas at no charge to the country. But in return, the company would retain the valuable byproducts of the gas-leaning process, like propane and butane, which it could sell at a profit. If Nigeria backed out at any point before the full 20-year term of the contract, it could be held liable for damages. Taken as a whole, it looked like an enormous commitment for Nigeria, one that might be met with skepticism when it finally met the eyes of the ministry’s lawyers.
Around this time, a lawyer named Grace Taiga landed a new job at the ministry, as legal director. This was fortunate, because Quinn and Cahill had known Taiga for years, ever since she was at the Ministry of Defense and they were businessmen who occasionally won contracts from it. For about a year leading up to the submission of P.&I.D.’s proposal, Quinn and Cahill sent Taiga and one of her daughters just a bit more than $25,000 in incremental payments. Quinn also took Taiga’s colleague, a Ministry employee named Taofiq Tijani, to dinner at Chopsticks, a Chinese restaurant in Abuja. The cost of that dinner was recorded in accounting books as $2,800. (A Chinese dinner does not cost $2,800 in Abuja.) Then, shortly before the contract was signed, Cahill sent another $5,000 from a bank in Cyprus to Taiga’s daughter’s account, which was coded as a “commission payment.”
Taiga sent the contract to her boss, Rilwanu Lukman, the minister of petroleum resources. It wasn’t much: 20 pages of mostly boilerplate language, drawn up on the ministry’s green-bordered stationery. It was more like an outline than a fully developed proposal for a multimillion-dollar gas deal. But Taiga assured Lukman in a memo that it would be “a leap forward” for Nigeria. On Jan. 11, 2010, Lukman, Quinn and Taiga signed their names. The deal was done.
Days later, a man named Neil Hitchcock — P.&I.D.’s only full-time employee — wrote to Cahill, saying he needed $1.5 million to begin clearing the ground for the facility. But P.&I.D. did not have $1.5 million. The plan had been to raise capital for the project on the basis of the signed 20-year contract, then bring on engineers and laborers. This was how they’d always operated in Nigeria.
In June, Quinn opened his morning paper to an unwelcome twist. The oil-drilling company that Nigeria had promised would supply the wet gas had decided to keep it; the gas turned out to be useful for maintaining pressure inside the wells. Quinn might have picked up the phone and protested to his friends inside the government, but most of them were gone. A new president had recently come into office. Lukman had been replaced. In February 2011, Hitchcock sent a text message that suggested the company was in dire straits. “In view of the rapidly deteriorating situation here, I see no option but to liquidate some P.&I.D. assets,” he wrote. “With your approval, I propose to sell the Honda Civic.” Quinn emailed the new president, Goodluck Jonathan, but his appeal went nowhere.

To a well-seasoned observer, all of this would have seemed like a pretty average case of what investors call “political risk.” When doing business in a corrupt country, it’s not at all uncommon that a new group takes power, then reneges on its predecessor’s deals. It happened all the time in Nigeria, which Transparency International ranks as one of the most corrupt places in the world, on par with Afghanistan and Guatemala. The whole affair seemed destined to melt without a trace.
But the contract had been drawn with a trapdoor at Article 20, a clause that transported you across the world. In the event of a dispute between the parties, nobody would go to court. They would settle their differences in a process called international arbitration, which had different rules than a trial and was closed to the press. “The venue of the arbitration shall be London,” the contract specified.
Quinn and Cahill hadn’t laid a single pipe for the gas-leaning facility, but this fact was immaterial. When the arbitration finished, the government of Nigeria had been thoroughly defeated. The decision was in P.&I.D.’s favor. The damages were $6.6 billion.
International arbitration is one of those elaborate little wheels in the global financial system that spin constantly in the background without anybody hearing the sound. Every day in financial capitals like Geneva, London and Paris, arbitration panels hand down decisions in every conceivable kind of contest, from institutions with nothing-to-see-here names: the International Centre for Settlement of Investment Disputes, the International Chamber of Commerce. Parties come here precisely because they have agreed to steer clear of the courts, and if all goes well they don’t interact with the local judicial system at all. Billions of dollars can change hands inside these rooms without a flicker of news coverage ever appearing.
The system was designed as an efficient, intercontinental fast lane beside the traffic jam of traditional justice. In the decade after the Second World War, when countries were eager to bind themselves together as trading partners, they worried about what might happen if disputes arose across borders. Where was the United Nations of business? To remedy the problem, a group of 24 nations signed a landmark arbitration treaty in 1958. Other treaties followed, until arbitration became a part of doing business in nearly every country in the world. As the sociologist Pierre Bourdieu put it, arbitration was a part of “the global logic of the new world legal order” — an order, it was hoped, in which enemies would turn into business partners.

Most of these arbitration cases wouldn’t generate headlines even if the doors were flung open. Many are just a couple of businesses fighting over money. Then there’s a subset of cases in which a business, or a single investor, can bring a claim against a sovereign state — many of these manage to be equally unremarkable. In 2012, a Swedish nuclear-power company took Germany to arbitration for phasing out its nuclear program ahead of schedule — the German government was spooked by the Fukushima disaster — and received more than one billion euros in the settlement.
Lawyers who practice in the area see it as a way to keep global commerce flowing smoothly. “If you didn’t have this system, you’d have what there used to be, which was gunboat diplomacy,” Gary Born, an international arbitration lawyer based in London, told me. “A foreign ministry, or somebody’s military, would take up cudgels on behalf of the local investor against the host state.” A country that doesn’t pay its arbitration bills can wind up blackballed by foreign investors. “Rather than hopelessly resist,” Born told me, “the overwhelming majority of parties voluntarily comply.”
Born estimates that about 1,600 arbitration cases are filed every year in which one party is an investor and the other party is a state or state-owned enterprise, but the opacity of the system makes exact figures impossible to get. In some arbitrations, we know the parties, but the specific details of the proceedings remain private. In a majority, however, the existence of the arbitration itself is never disclosed. Some investors see discretion as a selling point; you don’t want to find yourself in The Financial Times whenever you have to pay a lawyer. But when it comes to disputes between investors and sovereign states — in which public money and the public welfare are at stake — the secrecy has drawn criticism as a potentially serious flaw.
“If it was in court, it would be public,” Stephan Schill, a professor of international law at the University of Amsterdam, says of the P.&I.D. affair. “The press would monitor it, and would immediately pick out problems. The confidentiality is a big problem. It makes it easier to hide corruption.”

In the summer of 2015, representatives for both sides took their seats in a conference room in a building called the International Dispute Resolution Centre on Fleet Street. Lord Leonard Hoffman, an affable South African, presided over a three-member panel. Many arbitrators are elderly retired judges like Hoffman. The proceedings occasionally have the vibe of a “closed and arcane European club,” as one historian put it. The purpose of the hearing was to calculate damages.

Quinn had prepared a 34-page witness statement to establish his bona fides and show that P.&I.D. could have delivered on its end of the deal were it not for Nigeria’s reneging. He sketched out his track record. One day in 1970s Dublin, when Quinn and Cahill were still managing bands, they were approached by a Geneva-based exporter who worked in West Africa and evidently recognized that the backroom skills of a band manager could be more profitably applied to the import-export trade. Soon, they were exporting machine components and beer to West Africa on their own. From there, Quinn had expanded to projects that included restoring an aging fleet of Scorpion tanks; supplying the Nigerian government with rescue boats and training on how to operate them; fixing an offshore crude-loading platform in the Niger River Delta. The testimony gave the impression of what one Niger Delta oilman I spoke to called “soak time” — the long years in-country that gave you a feel for how things worked.
But the colorful biography omitted a salient detail: the thousands of dollars that Quinn and Cahill had paid to Taiga and others. The payments were a well-kept secret — Taiga wasn’t about to confess to having committed a crime — so Nigeria’s lawyers didn’t learn about them, and the three-member panel of arbitrators stayed in the dark. Hoffman found against Nigeria.

And this is where the structure of the deal revealed its true asymmetry. The original contract said that Nigeria had to give P.&I.D. wet gas not for a year or two, but for 20 years. Nigeria had failed to do this. Even though P.&I.D. hadn’t yet spent a penny on construction, Nigerian law — like British law — held that the party who breached a contract had to make the other party whole by paying them the amount they would have made had the contract been fulfilled. What this meant: When Nigeria paused on the wet gas, a legal wire was tripped. Nigeria owed P.&I.D. for two decades of hypothetical future profits from the sale of gas byproducts they had never processed, in a facility they had never built. But how much was that?
P.&I.D. had commissioned a report by a consulting firm, Berkeley Research Group, which laid out estimates of revenue and cash flow if the project had come to fruition. Financiers use something called a “discount rate” to calculate the value of future profits, taking into account all the risks that might be involved. The greater the risk of an investment, the higher the discount rate, and the lower the present-day value. Investments in Nigeria were considered risky because of political instability and corruption, so the standard discount rate at the time was more than 10 percent; the Berkeley report used 2.6 percent. On another page of the report, Berkeley predicted that oil — whose price historically correlates with that of natural-gas byproducts — would rise steadily, year after year, to $115 a barrel in 2024; but commodity prices fluctuate for all sorts of reasons, and today oil trades for $75 a barrel. One lawyer I interviewed, who has handled many investor-state arbitrations, called these calculations “simply primitive.” (Berkeley Research Group declined to comment.) Nigeria’s lawyers tried weakly to whittle it all down, because Quinn and Cahill “had done nothing” yet expected “an income for 20 years,” but it didn’t persuade Hoffman. Was the contract violated? It was. If so, how much was owed? Hoffman came to a figure: $6.6 billion, with interest at 7 percent, or about a million dollars a day.

When I spoke to Hoffman last spring, I found him affable and quick, with a wry sparkle. He noted that Nigeria’s lawyers had never asked for any discovery from P.&I.D. They never disputed the fact that Quinn and Cahill were qualified to build the gas plant, even though they had never built one before. And of course, they never raised the bribery. “They made no attempt to bring it to our attention,” he marveled in his plummy South African drawl. This was true. But they couldn’t have brought it to his attention, because it hadn’t been uncovered — not yet. In the middle of discussing the fatal weakness of the defense, the corners of Hoffmann’s mouth curled up, as though welcoming some private realization.
“Why are you smiling?” I asked.
“Because I see it is a very strange sort of case,” he said.
By the time Hoffman’s decision came down in January 2017, Nigeria once again had a new president: Muhammadu Buhari, who in the 1980s was the country’s military dictator. That spring, Buhari and his cabinet tried to settle with P.&I.D., but negotiations broke down. In September, P.&I.D. gave notice that it intended to “enforce the award” — to begin the process of extracting payment. Buhari had his back against the wall. He would have to surrender a sum of taxpayer dollars that equaled five times the budget for education and 10 times the budget for public health.
But there was a second option. As early as 2016, lawyers for Nigeria were urging government officials to dig into the mysterious company’s background, noting that the “offshore structure of P.&I.D., its apparently small size and lack of significant track record” were crying out to be investigated. Britain’s rules of arbitration said that if an award had been obtained by fraud, and caused “substantial injustice” to the losing party, that party could ask a civil court to overturn what the arbitration panel had done in private. In the history of arbitration, the courts had seldom seen fit to overturn what a panel had decided.
Buhari assigned the investigation to his attorney general, Abubakar Malami, who cut a flamboyant figure. Having come into office with promises to clean up corruption, Malami had quickly become a target of corruption allegations himself. The muckraking website Sahara Reporters would accuse him of abusing his office for profit, buying foreign cars and luxury properties for himself and his sons. “There was a general sense in Nigeria that Malami was irredeemably corrupt, and used the corruption to feather his own nest,” Farooq Kperogi, a Nigerian American professor and political columnist, told me. (Malami did not respond to multiple requests for comment. In a memoir published last year, he wrote that he had been unfairly persecuted for his “fancy dressing and expensive cars.”)
These allegations tarnished Malami’s public image, but the P.&I.D. award was quickly becoming the defining issue of his tenure, as headlines chastised the government for the astronomical loss. “Perhaps he felt that it was an opportunity for him to be seen to be doing something,” Kperogi says. “Or maybe he thought, Why should so much money leave the country if I’m not getting a piece of it?”

Malami tapped the agency inside the Nigerian state tasked with investigating corruption, the Economic and Financial Crimes Commission. A thinly staffed unit with a mixed reputation, the E.F.C.C. was established in 2003, initially to combat money laundering. Officers have a thankless, dangerous job: On more than one occasion they have been targeted by assassins. In 2010, a top investigator was shot and killed in his own home.
Interviewing employees at the Ministry of Petroleum Resources, the E.F.C.C. concluded that the approval of the contract had “significantly hinged” on the recommendation of Grace Taiga. Bank records showed deposits that lined up perfectly with major events in the timeline of the contract. In September 2019, investigators arrested Taiga, interrogated her for three weeks, then sent her to prison pending trial. She claimed that the suspicious cash deposits were from the sale of a car, or maybe property she had sold from her late mother’s estate. She was charged with corruption.

A kind of frenzy seemed to take hold of investigators. On their paradoxical mission to help the Nigerian state by proving how corrupt its bureaucrats really were, the agents were accused of coloring outside the lines of the law. There was an Irishman named James Nolan, who met Quinn in Dublin in the 1990s and worked as a part-time manager for P.&I.D. The E.F.C.C. arrested him in Abuja. “I was asked to sign a document stating that the P.&I.D. project was an orchestrated scam, intended to defraud the Nigerian government,” he later wrote in a statement. He declined, so they detained him for 13 months in Kuje Prison, which was overcrowded and had no running water and frequent blackouts. Nolan’s bipolar disorder flared, and his teeth rotted. (The E.F.C.C. did not respond to multiple requests for comment.) Eventually the government released him, charged him with money laundering and confiscated his passport. (Nolan did not appear at trial, and his current location is unknown.)
The government hired a team of white-shoe lawyers to pick up where the E.F.C.C. left off. The lawyers filed motions in U.S. courts to seize additional bank records. A trail of suspicious transactions beckoned them. Between 2008, when P.&I.D. started preparing the gas-leaning plan, and 2010, when the contract was signed, more than $10 million in cash had been withdrawn from its accounts. The day before Quinn met Rilwanu Lukman, the minister of petroleum resources, $84,000 was withdrawn. There were two withdrawals of $5,000 each the day before a “crucial” meeting with Lukman a few months later. (Lukman died in 2014, before the E.F.C.C. investigation began.) Taofiq Tijani, the ministry employee, told investigators that after the dinner at Chopsticks restaurant, a P.&I.D. employee threw a black bag containing $50,000 into the trunk of his car. (Tijani testified against P.&I.D. and received a nonprosecution agreement; he died in 2021.)

To pretend that all of this was out of the ordinary would, of course, be totally naïve. “It’s really difficult to do business in Nigeria without being solicited to pay a bribe,” Steven Powell, a forensics lawyer who frequently works there, told me. Diran Fawibe, a former staff member at the Nigerian National Petroleum Company, told me that Quinn and Cahill probably “knew that Nigeria is a corrupt country and that they could easily get people” to bend the rules.
But Nigeria asserted that Quinn and Cahill took the rule-bending to the furthest possible fringes: They weren’t paying bribes to lubricate an otherwise-solid project; they seemed to be paying bribes because they barely had a project at all. An early drawing of the wet-gas unit was a ripped-out piece of lined paper with hand-drawn pipelines on it, squiggles of blue marker representing water. A later drawing — the one they showed the Ministry — was a screenshot they took from designs for a different facility.
By the end, the 34 bundles of evidence told a story that one lawyer for Nigeria categorized as “industrial scale” fraud. The former band managers, they argued, had shaken down a sovereign state for $6.6 billion, for failing to fulfill an illegally procured contract that relied on copied plans for a different project. If there had ever been a case that cried out for a “substantial injustice” challenge, this one seemed to be it.
In 2020, Nigeria made its case to a judge in the High Court of Justice. The judge, Sir Ross Cranston, confronted what he called an “unprecedented” situation. As P.&I.D.’s lawyers noted, you couldn’t go messing with an arbitration award just because a few bribes had been uncovered many years after the fact; the whole essence of arbitration was finality. At the same time, the judge wrote, if he prevented Nigeria from going to trial, the British legal system might make itself an “unwitting vehicle” to an intercontinental fraud. He decided to let the case go forward. P.&I.D. would become a rarity among the 1,600 cases filed every year: a private arbitration that erupted into public view.
As expensive as arbitration may be, litigation is usually worse. In 2019, an arbitration panel ruled that Pakistan owed $6 billion to an Australian mining company, Tethyan, after Pakistan violated Tethyan’s contract to exploit a few mining plays in the country’s southwest. When Pakistan dragged its feet on payment, Tethyan took it to court. The company’s legal fees ran to $59.4 million.

Nigeria was a sovereign state with a G.D.P. of more than $470 billion. P.&I.D. had put its Honda Civic up for sale. The company was essentially a financial abstraction, a piece of paper that might or might not be worth a fortune (the award was now $11 billion with interest). It all depended on the outcome of the trial.
The solution to the money problem came from a lawyer named Seamus Andrew, who had represented P.&I.D. in arbitration. Andrew worked in litigation finance — he took on cases with a high possible reward, then found investors to fund the court battle. After P.&I.D. won the arbitration, Andrew foresaw a costly legal challenge, so he made a deal with VR Capital, a London-based hedge fund that focused on exactly these sorts of “specialized situations.”
In 2017, VR bought a 25 percent stake in P.&I.D. for $45 million, which allowed the company to pay for its own litigation in the civil trial. If the trial went their way, VR and Cahill would be entitled, on paper, to more than $1 billion each. Andrew’s share, on paper, would run into the hundreds of millions. Quinn died of cancer before the trial could start, and made an informal arrangement with his nephew, a lawyer named Trevor Burke, giving him a portion of his hypothetical share of the award. Taiga, who had been promised a small percentage of the future verdict, would get up to $500,000.
The trial opened in January 2023. Mark Howard, a partner at Brick Court Chambers and the lead lawyer for Nigeria, told a story about “a dishonest and venal cabal” who used “repeated lies” to pursue “riches beyond the dreams of avarice.” In Howard’s telling, Quinn and Cahill were scam artists who totally lacked the ability to construct a $500 million gas facility, but pretended otherwise in order to deceive the government of Nigeria. Then, when Nigeria backed out of the unfavorable deal, they tried to shake it down in arbitration.
One question that had puzzled Hoffmann, the judge who oversaw the arbitration, was why Nigeria’s lawyers had mounted such an inadequate defense. Howard said the answer was a devious plot: During the arbitration, P.&I.D. had somehow received copies of confidential legal documents from the Nigerian side — obtained, Howard argued, with more bribes. Banking records showed that P.&I.D. sent thousands of dollars to members of Nigeria’s legal team in the midst of the arbitration process. Howard argued that the reason P.&I.D. wanted these documents was to keep tabs on whether Nigeria had learned about the smoking-gun evidence that might have saved them from the arbitration award: the payments to Taiga

Howard then questioned P.&I.D.’s associates about all the cash payments recorded in the ledger books under euphemisms like “Dublin expenses” and “PR.” If the money hadn’t paid bribes, what was it for? Cahill and colleagues described them variously, in internal documents and in court, as: “Carry-around money”; “Brown envelopes”; “round sums”; fuel for “high-value transactions where confidentiality is required”; money to be used “in case they were stopped by an armed robber”; “doodles.” In the witness box, Cahill denied that P.&I.D. had paid bribes in Nigeria or during the arbitration. (He could not be reached for comment.) Testifying by video link from Nigeria, Taiga said that the money from Quinn was for “medical expenses,” not favors. By the time Howard got around to the engineering drawings that his opponents seemed to have copied from another project, it was hard to imagine how they could ever emerge from the deep crater he had placed them in. 
When it was P.&I.D.’s turn, its lawyers made a smart, steely case. David Wolfson, a lawyer with the commercial law firm One Essex Court, told a story in which the villain was the Nigerian bureaucracy. Nigeria had put up a weak defense at arbitration, so it lost. It should have known how important the case was, but it didn’t snap into action. Too bad, that’s life. Then, faced with admitting to the public how ineffectual it had been, it decided not to pay its bills and instead dispatch the E.F.C.C. and the national police to clean up after it, inventing a pattern of fraud from a list of humdrum bank withdrawals. P.&I.D.’s lawyers argued that the case was not about bribery; it was about “the sadly familiar Nigerian phenomenon of institutional incompetence.” 
The judge, Robin Knowles, disagreed, and in October, he ruled in favor of Nigeria, overturning the award and leaving P.&I.D. with nothing. The case demonstrated “what some individuals will do for money,” he wrote, “giving no thought to what their enrichment would mean in terms of harm for others.” He referred Andrew for a disciplinary hearing with the Bar Standards Board, for his “indefensible” handling of Nigeria’s internal documents. But he also criticized the vehicle: the arbitration system itself. “An open process allows the chance for the public and the press to call out what is not right,” he wrote. But arbitration happens in private. 
Andrew told me that the verdict was unfair to him, and says he is seeking an appeal. “I believe that I acted in accordance with my professional duties,” he wrote in an email, “which included a strict duty of confidentiality to my client.” P.&I.D.’s lawyers wrote that they were “disappointed with the outcome.” But the Nigerian press saw it as a wake-up call about the need to “checkmate the reckless expenditure of public funds” — to make sure that the government actually knew whom it was doing business with. In an editorial, The Guardian, a Nigerian daily newspaper, urged the country to look “beyond the euphoria” of Knowles’s ruling and implement reforms, to prevent the same thing happening again. 
Knowles’s decision rankled many prominent members of the arbitration profession, who saw it as gratuitously chastising an otherwise well-meaning group. “These abuses happen with extraordinary infrequency,” Gary Born told me. He was right. But the abuses that do happen can have outsize consequences when countries wind up staring down the barrel. Bryant Garth, a law professor who wrote the standard history book on arbitration, told me that the P.&I.D. process showed the danger of the arbitration system’s being manipulated by a greedy actor. “It treats the state as if it’s just another business,” he said, “rather than the representative of the people.” 
For months while I was reporting this article, I tried to track down Grace Taiga. But after employing all the usual channels, I came up empty. Eventually I hired a Nigerian journalist and fixer to help me. He found that since her initial arrest in 2019, Taiga had been in and out of prison — at one point, she skipped out on bail and was rearrested. The reason seemed to be that her kidneys were failing, and she was undergoing dialysis. This meant that at least that part of her testimony, the medical trouble, was true. Maybe that was one reason she needed the money from Quinn and Cahill. 
Then, in early September, the fixer called me to say that he had learned from a source inside the E.F.C.C. that Taiga was dead. According to the source, the cause was cancer, but there weren’t any other details. The Ministry of Petroleum Resources had no information. “Death registration is not common in Nigeria,” the fixer wrote. I wondered whether her two years in prison had worsened her health problems. (Her daughter, who was also implicated in the scheme, could not be reached for comment.) 
The fact that the small-time local bureaucrat — and not the investors or the lawyers — had suffered the most severely spoke to the real-life consequences of financial fraud, which often seems so abstract and opaque. I went back to the court records to reread Taiga’s texts. I found the familiar flagrant corruption. But in light of her death, I also saw a side that seemed painfully trusting. In 2014, she texted Cahill excitedly, dreaming of the windfall that would never come. “I keep remembering Papa telling me Grace u will be so wealthy,” she wrote, using her nickname for Quinn. “u will travel all over d world.” Taiga made the smallest gain and paid the highest price. 
"""

llm = ChatOpenAI(model=GPT_4_TURBO_MODEL, temperature=0.3)
template = """
Use the given format to extract information from the following input: {input}. Make sure to answer in the correct format
"""
prompt = PromptTemplate(template=template, input_variables=["input"])

json_schema = {
    "type": "object",
    "properties": {
        "summary": {
            "title": "Summary",
            "description": "The article summary", "type": "string"
        },
        "entities": {
            "title": "Entities",
            "description": "People, companies, governmental bodies, and other important entities mentioned in the article",
            "type": "string"
        },
        "sentiments": {
            "title": "Sentiments",
            "description": "The sentiment for each of the entities in the article",
            "type": "string"
        }
    },
    "required": ["summary", "entities", "sentiments"],
}

chain = create_structured_output_chain(json_schema, llm, prompt, verbose=False)

print(chain.run(TEST_TEXT))
