#!/usr/local/bin/python
# -*- coding: utf-8 -*-

import asyncio
from langchain_core.documents.base import Document
from ftfy import fix_encoding

from langchain_map_reduce import (
    GPT_3_MODEL,
    GPT_4_MODEL,
    GPT_4_TURBO_MODEL,
    default_text_splitter,
    get_summarizer,
)


TEST_TEXT: str = fix_encoding("""
Ian Kevin Curtis (15 July 1956 – 18 May 1980) was an English singer, songwriter and musician. He was best known as the lead singer, lyricist and occasional guitarist of the post-punk band Joy Division, with whom he released the albums Unknown Pleasures (1979) and Closer (1980). He was noted for his unique dancing style influenced by his experiences with epilepsy, as well as his dark baritone voice. Retrospectively viewed as "one of the finest songwriters of a generation," his intensely introspective and dark lyricism has provoked "visceral and raw emotions" among fans.[2] He was also noted for his distinct on-stage behaviour.[3]
Curtis had epilepsy and depression and died by suicide on the eve of Joy Division's first North American tour, shortly before the release of Closer. Shortly after his death, the three surviving members of the band renamed themselves New Order. Despite their short career, Joy Division have exerted a wide-reaching influence. John Bush of AllMusic argues that they "became the first band in the post-punk movement emphasizing not anger and energy but mood and expression, pointing ahead to the rise of melancholy alternative music in the '80s".[1] According to critic Simon Reynolds, Joy Division's influence has extended from contemporaries such as U2 and the Cure to later acts including Interpol, Bloc Party, Fontaines D.C., and Editors, as well as rappers including Danny Brown and Vince Staples.[4][5]
Ian Kevin Curtis was born at the Memorial Hospital in Stretford on 15 July 1956, and grew up in a working-class household in Macclesfield.[6] He was the first of two children born to Doreen and Kevin Curtis.[7] From an early age, he was a bookish and intelligent child, displaying a particular flair for poetry. By passing his 11-Plus exam – sat by all primary school children – he gained a place at the age of 11 at Macclesfield's  boys’ grammar school, The King's School. It was here that he developed his interests in philosophy, literature, and eminent poets such as Thom Gunn.[8] While at King's School, he was awarded several scholastic awards in recognition of his abilities, particularly at the ages of 15 and 16. The year after Curtis graduated from King's School, the family purchased a house from a relative and moved to New Moston.[9]
As a teenager, Curtis chose to perform social service by visiting the elderly as part of a school programme. While visiting, he and his friends would steal any prescription drugs that they found and later take them together as a group. On one occasion when he was 16,[10] after consuming a large dosage of Largactil he and his friends had stolen, Curtis was discovered unconscious[11] in his bedroom by his father and was taken to hospital to have his stomach pumped.[12]
Curtis had held a keen interest in music since his early teenage years and was influenced by artists such as Jim Morrison and David Bowie.[13] Among Curtis's earliest experiences with music was in a church choir as a young kid, in his hometown of Macclesfield.[14][15] Curtis could seldom afford to purchase records, leading him to frequently steal them from local shops.[n 1] By his mid-teens, Curtis had also developed a reputation among his peers as a strong-willed individual, with a keen interest in fashion.[17]
Despite gaining nine O-levels at King's School[18][19] and briefly studying A-Levels in History and Divinity at St. John's College, Curtis soon became disenchanted with academic life and abandoned his studies at St. John's College to find a job.[20] Nonetheless, Curtis continued to focus on the pursuit of art, literature and music, and would gradually draw lyrical and conceptual inspiration from ever more insidious subjects.[21]
Curtis obtained a job at a record shop in Manchester City Centre,[22] before obtaining more stable employment within the civil service. His employment as a civil servant saw Curtis initially deployed to Cheadle Hulme, where he worked for several months with the Ministry of Defence,[23] before he was offered alternative employment within the Manpower Services Commission in a building at Piccadilly Gardens. He later worked as a civil servant in Woodford, Greater Manchester although, at his request, approximately one year later[24] Curtis was posted to Macclesfield's Employment Exchange, where he worked as an Assistant Disablement Resettlement Officer.
On 23 August 1975, Curtis married Deborah Woodruff, to whom he was introduced by a friend, Tony Nuttall.[25] Ian and Deborah initially became friends and then began dating in December 1972, when both were 16 years old.[26][n 2] Their wedding service was conducted at St Thomas' Church in Henbury, Cheshire. Curtis was 19 and Woodruff 18. They had one child, a daughter named Natalie, born on 16 April 1979.[27] Initially, the couple lived with Ian's grandparents, although shortly after their marriage the couple moved to a working-class neighbourhood in Chadderton,[28] where they paid a mortgage while working in jobs neither enjoyed. Before long, the couple became disillusioned with life in Oldham and remortgaged their house[29] before briefly returning to live with Ian's grandparents. Shortly thereafter, in May 1977, the couple moved into their own house in Barton Street, Macclesfield,[10] with one of the rooms of the property becoming colloquially known between the couple as Curtis's "song-writing room".[30]
At a July 1976 Sex Pistols gig at Manchester's Lesser Free Trade Hall, Curtis encountered three childhood school friends named Bernard Sumner, Peter Hook and Terry Mason.[19] The trio informed Curtis—whom they had seen at earlier punk gigs at The Electric Circus—of their intentions to form a band[10] and Curtis informed them of his then-recent efforts to do likewise,[31] before proposing himself as both their singer and lyricist. Initially, Mason became the band's drummer, but his rehearsal sessions were largely unproductive and he briefly became the band's manager.[32] The group then unsuccessfully attempted to recruit several drummers before selecting Stephen Morris in August 1977.[33] The band was later managed by Rob Gretton, who—having already seen Joy Division perform live at local venues such as Rafters—offered to become their manager in 1978.[34]
Initially, the band named themselves "Warsaw", from the song title “Warszawa” on David Bowie's then-recent album Low, but as this name somewhat conflicted with that of a London-based group named Warsaw Pakt they renamed themselves Joy Division.[35] This moniker was derived from the 1953 novella The House of Dolls, which featured a Nazi concentration camp with a sexual slavery wing called the "Joy Division". The cover of the band's first EP depicted a drawing of a Hitler Youth beating a drum and the A-side contained a song, "Warsaw", which was a musical retelling of the life of Nazi leader Rudolf Hess.[36]
After founding Factory Records[37] with Alan Erasmus, Tony Wilson signed the band to his label following its first appearance on the TV music show he hosted, So It Goes, in September 1978. This appearance had been largely prompted by an abusive letter sent to Wilson by Curtis and saw the band play the song "Shadowplay".[12][n 3]
While performing with Joy Division, Curtis became known for his quiet and awkward demeanour and a unique dancing style[39] reminiscent of the epileptic seizures he began experiencing in late 1978. Although predominantly a singer, Curtis also played guitar on a handful of tracks (usually when Sumner was playing synthesizer; "Incubation" and a Peel session version of "Transmission" were rare instances when both Sumner and Curtis played guitar). Initially, Curtis played Sumner's Shergold Masquerader, but in September 1979 he acquired his own guitar, a Vox Phantom VI Special which had many built-in effects used both live and in studio.[40] This included a repeat effect misspelled as "replat" on the control panel. Curtis used the guitar on Joy Division's early 1980 European tour and in the video for "Love Will Tear Us Apart".[41]
Curtis's widow, Deborah, has claimed that in October 1979, Curtis began conducting an affair with the Belgian Annik Honoré who had been working at the Belgian embassy in London before becoming a journalist and music promoter.[42] They had first met at a gig held in Brussels that month.[43][44] Curtis was consumed with guilt over this affair due to being married[45] and the father of their baby daughter, but at the same time still yearning to be with Honoré.[46] On one occasion in 1980, Curtis asked Bernard Sumner to make a decision on his behalf as to whether he should remain with his wife or form a deeper relationship with Honoré; Sumner refused.[47] Honoré claimed in a 2010 interview that although she and Curtis had spent extensive periods together, their relationship had been platonic. Deborah Curtis has maintained that it was a sexual and romantic affair.[48] His bandmates recollected later that Curtis's friendship with Honoré led him to distance himself and become somewhat "lofty" with them.[44] This distance prompted occasional pranks at Curtis's and Honoré's expense. He became a vegetarian, likely at Honoré's behest since he was known to have consumed meat when not in her presence.[44]
Deborah has described Curtis as exhibiting a somewhat controlling attitude within their relationship, which had included minimising any opportunity for her to come into contact with other men, and insisting she vote for the Conservative Party at a local council election, the same as Curtis had done, to not "cancel his vote".[49][42][50][51]
Curtis began having epileptic seizures in late 1978; he was officially diagnosed with the condition on 23 January the following year,[52][n 4] with his particular case being described by doctors as so severe, his "life would [be] ruled to obsolescence by his severe epilepsy"[54] without the various strong dosages of medications he was prescribed. Having joined the British Epilepsy Association, Curtis was initially open to discuss his condition with anyone who inquired, although he soon became withdrawn and reluctant to discuss any issue regarding his condition beyond the most mundane and necessary aspects.[55] On each occasion it became apparent a particular prescribed medication failed to control Curtis's seizures, his doctor would prescribe a different anticonvulsant and his wife noted his being "full of renewed enthusiasm" that this particular formulation would help him bring his seizures under control.[56]
Throughout 1979 and 1980, Curtis's condition gradually worsened amid the pressure of performances and touring,[10] with his seizures becoming more frequent and more intense.[57] Following his diagnosis, Curtis continued to drink, smoke and maintain an irregular sleeping pattern—against the advice given to those with the condition.[54] The medications Curtis was prescribed for his condition produced numerous side effects, including extreme mood swings.[10][58] This change in personality was also observed by Curtis's wife, family and in-laws, who noted how taciturn he had become in his wife's company.[59] Following the birth of his daughter in April 1979, because of the severity of his medical condition, Ian was seldom able to hold his baby daughter in case he compromised the child's safety.[59]
"He saw it (Joy Division) going on without him. He felt very removed from it. With the epilepsy, he just knew he couldn't carry on with the performances. He'd sort of hit a pinnacle with Closer, and he knew he couldn't go on."
—Lindsay Reade, on Curtis's brief period of recuperation at her rural Bury household shortly before his suicide in May 1980.[44]
At the time of the recording of the band's second album, Curtis's condition was particularly severe, with him enduring a weekly average of two tonic-clonic seizures.[60] On one occasion during these recordings, Curtis's bandmates became concerned when they noted he had been absent from the recording studio for two hours.[61] The band's bassist, Peter Hook, discovered Curtis unconscious on the floor of the studio's toilets, having hit his head on a sink following a seizure.[62] Despite instances such as this, Hook stated that, largely through ignorance of the condition, he, Sumner and Morris did not know how to help. Nonetheless, Hook was adamant that Curtis never wanted to upset or concern his bandmates, and would "tell [us] what [we] wanted to hear" if they expressed any concern as to his condition.[62] In one incident, at a concert held before almost 3,000 people at the Rainbow in Finsbury Park in April 1980, the lighting technicians at the venue—contrary to instructions given to them by Rob Gretton prior to the gig—switched on strobe lights midway through Joy Division's performance, causing Curtis to almost immediately stagger backwards and collapse against Stephen Morris's drum kit in the throes of an evident photosensitive seizure. He had to be carried offstage to the band's dressing room to recuperate.[63]
When Curtis had recovered from this first seizure, he was adamant the band travel to West Hampstead to honour their commitment to perform their second gig of the evening at this location, although some 25 minutes into this second gig, Curtis's "dancing started to lose its rhythmic sense and change into something else entirely" before he collapsed to the floor and experienced the most violent seizure he had endured to date.[63]
Curtis's onstage dancing was often reminiscent of the seizures he experienced[64] and has been termed by some to be his "epilepsy dance".[65] Throughout Joy Division's live performances in 1979 and 1980, Curtis collapsed several times while performing and had to be carried off stage.[66] To minimise any possibility of Curtis having epileptic seizures, flashing lights were prohibited at Joy Division gigs; despite these measures, Bernard Sumner later stated that certain percussion effects would cause Curtis to have a seizure.[67] In April 1980,[68] Terry Mason was appointed as a minder to ensure Curtis took his prescribed medications, avoided alcohol consumption and got sufficient sleep.[68]
Regarding the choreography of Curtis's stage performances, Greil Marcus in The History of Rock 'n' Roll in Ten Songs quotes Jon Savage from Melody Maker: "Ian's mesmeric style mirrored the ever more frequent epileptic spasms that Deborah Curtis had to cope with at home."[69] Marcus remarked that Curtis's performance "might also have been a matter of intentionally replicating fits, re-enacting them, using them as a form of energy and a form of music."[70]
Curtis's final live performance with Joy Division was on 2 May 1980 at the High Hall of Birmingham University and included Joy Division's first and only performance of "Ceremony", later recorded by New Order and released as their debut single. The final song Curtis performed on stage with Joy Division prior to his death was "Digital".[n 5]
Following Curtis's first definite suicide attempt on 6 April 1980, Tony Wilson and his partner, Lindsay—expressing deep concerns as to Joy Division's intense touring schedule being detrimental to Curtis's physical and mental well-being[72]—invited him to recuperate at their cottage in Charlesworth in Derbyshire. While there, he is known to have written several letters to Honoré, proclaiming his love for her as he recuperated.[44][n 6]
By early 1980, Curtis's marriage to Deborah was floundering, as she had commenced divorce proceedings after he had failed to cease all contact with Honoré.[42][74][n 7] Curtis enjoyed solitude, but had never been mentally equipped for living alone.[75] He was having difficulty balancing his family obligations with his musical ambitions and his health was gradually worsening as a result of his epilepsy, thus increasing his dependency upon others.[42] On the evening before his death, Curtis informed Bernard Sumner of his insistence upon seeing his wife that evening.[76] He had also made firm plans to rendezvous with his bandmates at Manchester Airport the following day, before their departure for America.[46]
"Strange as it may sound, it wasn't until after his death that we really listened to Ian's lyrics and clearly heard the inner turmoil in them."
—Bernard Sumner, reflecting in November 2015 on the lyrics Curtis had written for Joy Division's second and final album, Closer[77]
On the evening of 17 May 1980, Curtis asked Deborah to drop her impending divorce proceedings; she replied that it was likely that he would have changed his mind by the following morning and then—mindful of his previous suicide attempt and also concerned that his state of anxiety and frustration might drive Curtis into an epileptic seizure—offered to spend the night in his company.[78] Deborah then drove to her parents' home to inform them of her intentions. When she returned to the couple's home at 77 Barton Street in Macclesfield, Cheshire, his demeanour had changed and he informed his wife of his intentions to spend the night alone, first making her promise not to return to the house before he had taken his scheduled 10 a.m. train to Manchester to meet up with his bandmates.[79]
In the early hours of the next morning, Curtis died by suicide at the age of 23.[80] He had used the kitchen's washing line to hang himself after having written a note to Deborah in which he declared his love for her despite his recent affair with Honoré.[n 8][33] Deborah found his body soon after. In her biography, Touching from a Distance,[82] Deborah recalls finding her husband's body and initially thinking that he was still alive before noticing the rope around his neck.[81] According to Tony Wilson,[83] Curtis spent the few hours before his suicide watching Werner Herzog's 1977 film Stroszek and listening to Iggy Pop's 1977 album The Idiot.[33]  Stark notes the significance of this album, as Pop's title was inspired by Dostoyevsky's novel The Idiot about the spiritually sensitive epileptic prince who was driven mad by the tragic and violent society in which he lived.[84]  His wife recollected that he had taken photographs of their wedding and their baby daughter off the walls, apparently to view them as he composed a note.[81] In the note, he didn't explicitly state that he was going to kill himself, and asked Deborah not to contact him for a while. It is not clear whether Curtis intended this to be a suicide note at the time of writing.[82]
At the time of Curtis's suicide, Joy Division were on the eve of their debut North American tour. Deborah has stated that Curtis had viewed the upcoming tour with extreme trepidation, not only because of his extreme fear of flying (he had wanted to travel by ship) but also because he had expressed deep concerns as to how American audiences would react to his epilepsy.[47] Deborah has also claimed that Curtis had confided in her on several occasions that he held no desire to live past his early twenties.[85][86] He had expressed to both Deborah and Honoré his deep concerns that his medical condition was likely to kill him,[87] in addition to causing him to receive mockery from audiences,[88] and that this mockery would only increase when performing before American audiences on the upcoming tour.[n 9]
According to Lindsay Reade, Curtis had informed her shortly before his death of his belief that, with his epilepsy, he could no longer perform live with the band. In addition, he had claimed that with the impending release of Closer, he believed the band had hit an artistic pinnacle.[44]
In a 2007 interview with The Guardian, Stephen Morris expressed regret that nobody had realised during Curtis's life the distress he was in, even though it was evident in his lyrics.[90][n 10] Bassist Peter Hook reflected on the tragedy of the timing of Curtis's death, just before what might have been a breakthrough to fame.[83] Hook also claimed that, prior to the release of the 2007 documentary Joy Division, a specialist in epilepsy had viewed the combination of drugs that Curtis had been prescribed for his condition and expressed concerns about the drugs' safety.[92]
Curtis's body was cremated at Macclesfield Crematorium on 23 May 1980, and his ashes were buried at Macclesfield Cemetery. A memorial stone, inscribed with "Ian Curtis 18–5–80" and "Love Will Tear Us Apart", was placed above his ashes.[93][n 11] This memorial stone was stolen in mid-2008.[95] A replacement, bearing the same inscription but in a sans-serif typeface, was placed in the same location.[96] A central "mowing" stone used to hold floral tributes was reported stolen from the grave in August 2019.[93]
Shortly after Curtis's cremation, Sumner, Hook and Morris—strongly aided by Rob Gretton—formed a new band. Initially calling themselves "The No Names" and playing largely instrumental tracks, they soon became "New Order".[97] Shortly after Curtis's death, Bernard Sumner inherited the Vox Phantom VI Special guitar Ian Curtis had acquired in September 1979; he used this instrument in several early New Order songs, including the single "Everything's Gone Green".[41]
Numerous New Order songs reference or pay tribute to Curtis. The tracks "ICB" (an abbreviation of 'Ian Curtis, Buried') and "The Him" from their debut album Movement both refer to his passing. The instrumental track "Elegia", released in 1985, was also written in his memory,[98] while the 2002 song "Here to Stay" was dedicated to Curtis as well as Rob Gretton and Martin Hannett.
Joy Division labelmates the Durutti Column paid tribute to Curtis in the form of "The Missing Boy", which appeared on their 1981 album LC. In 1990, Psychic TV released "I.C. Water", which was dedicated to Curtis. In 1999, the post-hardcore band Thursday released a song titled "Ian Curtis" on their debut album, Waiting, while in 2003, Xiu Xiu released the track "Ian Curtis Wishlist" on their second album, A Promise.[99]
Deborah Curtis has written a biographical account of their marriage, Touching from a Distance, which was first published in 1995. This biography details in part his relationship with Annik Honoré. Authors Mick Middles and Lindsay Reade released the book Torn Apart: The Life of Ian Curtis in 2006. This biography takes a more intimate look at Curtis and includes photographs from personal family albums and excerpts from his letters to Honoré during their relationship. Music journalist Paul Morley wrote Joy Division, Piece by Piece, writing about Joy Division 1977–2007; it was published in late 2007. The book documents all of his writings and reviews about Joy Division, from their formation until Tony Wilson's death.
The words "Ian Curtis Lives" are written on a wall in Wallace Street, Wellington, New Zealand.[100] The message, which appeared shortly after the singer's death in 1980, is repainted whenever it is painted over. A nearby wall on the same street on 4 January 2005 was originally emblazoned "Ian Curtis RIP", later modified to read "Ian Curtis RIP Walk in Silence" along with the incorrect dates "1960–1980".[101] Both are referred to as "The Ian Curtis Wall".[102] On 10 September 2009, the wall was painted over by Wellington City Council's anti-graffiti team.[103] The wall was chalked back up on 16 September 2009.[104] The wall was repainted on 17 September 2009, and has been removed and repainted on and off. A new and improved design, with correct dates and the original "Walk in Silence", was painted on the wall on 27 February 2013.[105] [106]In October 2020, in line with Manchester music and mental wellbeing festival Headstock, a large mural depicting a black and white portrait of Ian Curtis was painted on the side of a building on Port Street in Manchester's Northern Quarter by street artist Akse P19.[107][108]
In 2012, Curtis was among the British cultural icons selected by artist Peter Blake to appear in a new version of the Beatles' Sgt. Pepper's Lonely Hearts Club Band album cover.[109]
Curtis was portrayed by Sean Harris in the 2002 film 24 Hour Party People, which dramatised the rise and fall of Factory Records from the 1970s to the 1990s.
In 2007, a British biographical film titled Control about Curtis was released. This film was largely based upon Deborah Curtis's book Touching from a Distance.[110] The film was directed by the Dutch rock photographer and music video director Anton Corbijn, who had previously photographed the band and directed the video for their single "Atmosphere". Deborah Curtis and Tony Wilson were executive producers, while Todd Eckert of Clara Flora was the producer. Sam Riley, the lead singer of the band 10,000 Things, portrays Curtis, while Samantha Morton plays his wife, Deborah.
Control was debuted at the Cannes Film Festival on 17 May 2007 and received three awards at the Directors' Fortnight. Control portrays Curtis's secondary school romance with Deborah, their marriage, his problems balancing his domestic life with his rise to fame, his struggles with both his major depressive issues and his poorly medicated epilepsy and his later relationship with Annik Honoré.[111][112]
In 2014, the house in which Curtis ended his life went on sale. Upon hearing this news, a fan initiated a campaign via Indiegogo to raise funds to purchase the house with intentions to preserve the property as a  museum to Curtis and Joy Division.[113] The campaign only raised £2,000 out of the intended final goal £150,000. The money raised was later donated to the Epilepsy Society and MIND charities.[114]
Upon hearing of the failure of this project, an entrepreneur and musician named Hadar Goldman purchased the property, offering to pay a £75,000 compensation fee on top of the requested house price of £125,000 in order to secure the purchase of 77 Barton Street and thus reverse the transacted sale from a private purchaser, which at the time was already in progress.[115] Justifying his decision, Goldman stated he intended the property to act as a Joy Division museum and as a digital hub to support musicians and other artists worldwide.[115][116][117] As of 2023, this planned museum has not come to fruition.[118]
""")

docs = [Document(page_content=TEST_TEXT)]


async def run_chain():
    map_reduce_chain = get_summarizer(gpt_model=GPT_4_TURBO_MODEL, temperature=0.3)
    split_docs = default_text_splitter.split_documents(docs)
    reduced_summary = await map_reduce_chain.arun(split_docs)
    return reduced_summary


if __name__ == "__main__":
    summary = asyncio.run(run_chain())
    print(summary)

